package com.y3r9.c47.dog.script;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import org.apache.poi.ss.usermodel.Cell;
import org.junit.Test;

/**
 * The class DcdScripts.
 *
 * @version 1.0
 */
public final class DcdScripts {

    @Test
    public void excelToJava() throws IOException {
        POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream("d:/e/protocol.xls"));
        HSSFWorkbook wb = new HSSFWorkbook(fs);
        HSSFSheet sheet = wb.getSheetAt(0);
        StringBuilder out = new StringBuilder();
        StringBuilder err = new StringBuilder();
        for (int r = sheet.getFirstRowNum(), i = 1; r <= sheet.getLastRowNum(); r++) {
            HSSFRow row = sheet.getRow(r);
            HSSFCell lenghCell = row.getCell(3);
            if (lenghCell == null) {
                continue;
            }
            int length = 0;
            if (lenghCell.getCellType() == Cell.CELL_TYPE_NUMERIC) {
                length = (int) lenghCell.getNumericCellValue();
            } else {
                try {
                    length = Integer.parseInt(lenghCell.getStringCellValue());
                } catch (NumberFormatException e) {

                }
            }
            String name = row.getCell(1).getStringCellValue().trim();
            if (length > 0) {
                String codeName = dict.get(name);
                codeName = codeName == null ? name : codeName;
                if (codeName == null) {
                    err.append("dict.put(\"" + name + "\", \"\");\n");
                    codeName = name;
                }
                if (!"Filler".equals(codeName)) {
                    out.append("{ { " + i + ", null, " + length
                            + ", Encoding.ASCII}, { \"\", ValueType.STRING, false, \"" + codeName
                            + "\" } },\n");
                } else {
                    out.append("{ { " + i + ", null, " + length
                            + ", Encoding.ASCII }, { \"Filler\", null } },\n");
                }
                i++;
            }
        }
        if (err.length() > 0) {
            System.out.println(err.toString());
        } else {
            System.out.println(out.toString());
        }
    }

    @Test
    public void printDict() {
        dict.entrySet().forEach(entry -> {
            System.out.println(entry.getKey() + "\t" + entry.getValue());
        });

    }

    static Map<String, String> dict = new HashMap<>();

    static {
        dict.put("Transaction Amount", "TransAmt");
        dict.put("Amount other", "AmtOther");
        dict.put("Terminal Country Code", "TermCtryCode");
        dict.put("Terminal Verificaion Result", "TermVerRst");
        dict.put("Transaction Currency Code", "TransCurrCode");
        dict.put("Transaction Date", "TransDate");
        dict.put("Transaction Type", "TransType");
        dict.put("Unpredictable Number", "UnpredNum");
        dict.put("Application Interchange Profile", "AppInterProfile");
        dict.put("Application Transaction Counter", "AppTransCounter");
        dict.put("Issuer application data", "IssAppData");
        dict.put("ARPC+ARC", "APRC_ARC");
//        dict.put("首次存款数额", "FirstDepositAmount");
//        dict.put("存本取息利息", "CBQXInterest");
//        dict.put("账号﹕Account number", "AcctNo");
//        dict.put("分类帐名称", "ClassAcctName");
//        dict.put("其他语言名称", "OtherLangName");
//        dict.put("银行号", "BankNo");
//        dict.put("机构号 Institution Number", "InstNo");
//        dict.put("产品类型代码", "ProductType");
//        dict.put("产品子类代码", "ProductSubClass");
//        dict.put("预算值1", "Budget1");
//        dict.put("预算值2", "Budget2");
//        dict.put("预算值3", "Budget3");
//        dict.put("预算值4", "Budget4");
//        dict.put("预算值5", "Budget5");
//        dict.put("预算值6", "Budget6");
//        dict.put("预算值7", "Budget7");
//        dict.put("预算值8", "Budget8");
//        dict.put("预算值9", "Budget9");
//        dict.put("预算值10", "Budget10");
//        dict.put("预算值11", "Budget11");
//        dict.put("预算值12", "Budget12");
//        dict.put("分类帐价值", "ClassValue");
//        dict.put("跨货币金额", "KHBAmount");
//        dict.put("联行值", "LHZ");
//        dict.put("非跨货币价值交易", "FKHBJZTrade");
//        dict.put("周期月份", "PeriodMonth");
//        dict.put("周期日期", "PeriodDate");
//        dict.put("总帐分类码", "MainAcctClassCode");
//        dict.put("部门", "Depart");
//        dict.put("上次产品类型变更日", "LastProductChangeDay");
//        dict.put("特殊参考号标识", "SpecRefIndicator");
//        dict.put("特殊参考号借记、贷记标识", "CreditIndicator");
//        dict.put("Sweep标识", "SweepIndicator");
//        dict.put("延迟天数", "DelayDays");
//        dict.put("母帐号", "ParentAcctNo");
//        dict.put("Push Posting Ind", "PushPostingInd");
//        dict.put("Sec Access Ind", "SecAccessInd");
//        dict.put("Spcl Acc Ind", "SpclAccInd");
//        dict.put("受益代码", "BenifitCode");
//        dict.put("关闭标记Closure Flag", "ClosureFlag");
//        dict.put("Close Flag", "CloseFlag");
//        dict.put("库存限制金额", "StoreLimitAmount");
//        dict.put("客户号 Customer number", "CustNo");
//        dict.put("Swift号Swift number", "SwiftNo");
//        dict.put("记录号Rec number", "RecNo");
//        dict.put("客户名称GirdName", "GirdName");
//        dict.put("客户状态", "CustState");
//        dict.put("客户号3", "CustNo3");
//        dict.put("签约帐号", "SignAcct");
//        dict.put("账户分类", "AcctClass");
//        dict.put("账户开户机构", "AcctInst");
//        dict.put("主附卡标识", "MastSlaveIndicator");
//        dict.put("开卡机构", "IssueInst");
//        dict.put("卡产品号", "CardProductNo");
//        dict.put("卡介质类型", "CardMaterialType");
//        dict.put("卡类型", "CardType");
//        dict.put("交易日期", "TransDate");
//        dict.put("终端号", "TerminalNo");
//        dict.put("柜员号", "TellerNo");
//        dict.put("交易代码", "TransNo");
//        dict.put("记账日期POST DATE", "PostDate");
//        dict.put("日志号", "LogNo");
//        dict.put("时间", "Time");
//        dict.put("附加信息 APPEND INFROMATION", "AppendInfo");
//        dict.put("交易描述", "TransDesc");
//        dict.put("延期日期", "DelayDate");
//        dict.put("CHQ-NO-DAY", "CHONODay");
//        dict.put("BATCH NO", "BatchNo");
//        dict.put("新册号", "NewVolumeNo");
//        dict.put("新序号", "NewSeqNo");
//        dict.put("到期日", "ExpireDate");
//        dict.put("结清日", "SettleDate");
//        dict.put("产品代码", "ProductNo");
//        dict.put("开户行", "OpenBank");
//        dict.put("账号状态", "AcctState");
//        dict.put("Secondary Flag", "SecondaryFlag");
//        dict.put("账号 Account number", "AcctNo");
//        dict.put("渠道", "Channel");
//        dict.put("主账户标识", "MainAcctIndicator");
//        dict.put("Magnetic Passbook Account Number", "MagPassbookAcctNo");
//        dict.put("Magnetic Passbook Type", "MagPassbookType");
//        dict.put("Magnetic Passbook Ser Number", "MagPassbookSerNo");
//        dict.put("Out Check Digit", "OutCheckDigit");
//        dict.put("From Currency", "FromCurrency");
//        dict.put("To Currency", "ToCurrency");
//        dict.put("Native Currency", "NativeCurrency");
//        dict.put("Change Amount", "ChangeAmount");
//        dict.put("No From Amount. It indicates whether there will be amount in the from amount field. It has values of N or Y.", "NoFromAmount");
//        dict.put("Note Government Bond Indicator", "NGBIndicator");
//        dict.put("Account Name", "AcctName");
//        dict.put("NGB Year", "NGBYear");
//        dict.put("Issue Number", "IssueNo");
//        dict.put("NGB Amount", "NGBAmount");
//        dict.put("Account open Date", "AcctOpenDate");
//        dict.put("Interest From Date", "InterestFromDate");
//        dict.put("Maturity Date", "MaturityDate");
//        dict.put("Type", "Type");
//        dict.put("Customer Name", "CustName");
//        dict.put("Term Length (ZZZ9)", "TermLength");
//        dict.put("Transaction Date", "TransDate");
//        dict.put("Date – 1 (ddmmyyyy)", "Date1");
//        dict.put("Date – 2 (ddmmyyyy)", "Date2");
//        dict.put("Rate (Z9.9999)", "Rate");
//        dict.put("Percentage Sign ‘%’", "PercSign");
//        dict.put("Pay Method (Text from TXTM)", "PayMethod");
//        dict.put("Frequency", "Frequency");
//        dict.put("Currency", "Currency");
//        dict.put("Product Name", "ProductName");
//        dict.put("Teller Number", "TellerNo");
//        dict.put("Supervisor Number", "SuperNo");
//        dict.put("Pledge Number", "PledgeNo");
//        dict.put("Sequence Number", "SeqNo");
//        dict.put("Old type", "OldType");
//        dict.put("Roller Type", "RollerType");
//        dict.put("Open Bank", "OpenBank");
//        dict.put("Transaction Branch", "TransBranch");
//        dict.put("Description Text", "DescText");
//        dict.put("From Amount", "FromAmount");
//        dict.put("From Currency Code", "FromCurrencyCode");
//        dict.put("To Amount", "ToAmount");
//        dict.put("To Currency Code", "ToCurrencyCode");
//        dict.put("Exchange Rate", "ExchangeRate");
//        dict.put("Commission", "Comission");
//        dict.put("Change", "Change");
//        dict.put("Time (HHMMSS)", "Time");
//        dict.put("Product Indicator", "ProductIndicator");
//        dict.put("Account Type", "AcctType");
//        dict.put("Currency Code", "CurrencyCode");
//        dict.put("Full Name", "FullName");
//        dict.put("Address 1", "Address1");
//        dict.put("Address 2", "Address2");
//        dict.put("Address 3", "Address3");
//        dict.put("Postcode", "Postcode");
//        dict.put("State", "State");
//        dict.put("Product Description", "ProductDesc");
//        dict.put("SKLI POID", "SkliPoid");
//        dict.put("Name – 1", "Name1");
//        dict.put("Name – 2", "Name2");
//        dict.put("Branch Phone", "BranchPhone");
//        dict.put("Customer Number", "CustNo");
//        dict.put("Account type", "AcctType");
//        dict.put("Fund Code", "FundCode");
//        dict.put("Withdrawal Type", "WithdrawalType");
//        dict.put("Open Date(DDMMCCYY)", "OpenDate");
//        dict.put("Maturity Date(DDMMCCYY)", "MaturityDate");
//        dict.put("Term Length", "TermLength");
//        dict.put("Term Basis", "TermBasis");
//        dict.put("Interest Rate", "InterestRate");
//        dict.put("Interest Payment", "InterestPayment");
//        dict.put("Interest payment Amount", "InterestPayAmount");
//        dict.put("Payment Amount", "PaymentAmount");
//        dict.put("Issue Date(DDMMCCYY)", "IssueDate");
//        dict.put("Volume Number", "VolumeNo");
//        dict.put("Reason Code", "ReasonCode");
//        dict.put("Voucher Type", "VoucherType");
//        dict.put("Old Number", "OldNo");
//        dict.put("New Number", "NewNo");
//        dict.put("Supervisor Id", "SuperId");
//        dict.put("Teller id", "TellerId");
//        dict.put("Issue Branch name", "IssueBranchName");
//        dict.put("Product Description", "ProductDesc");
//        dict.put("Customer Type", "CustType");
//        dict.put("Boss Name", "BossName");
//        dict.put("Gender", "Gender");
//        dict.put("ID Type", "IDType");
//        dict.put("ID Number", "IDNo");
//        dict.put("Name – first part", "FirstName");
//        dict.put("Name – second part", "SecondName");
//        dict.put("Terminal Number", "TerminalNo");
//        dict.put("Teller Name", "TellerName");
//        dict.put("Journal Number", "JournalNo");
//        dict.put("Amount", "Amount");
//        dict.put("Balance", "Balance");
//        dict.put("Account Balance – Euro (if “in” currency)", "AcctBalance");
//        dict.put("Currency “EUR” (if “in” currency)", "Currency");
//        dict.put("Swift Reference", "SwiftRef");
//        dict.put("Base Foreign Currency Account Number", "BFCAcctNo");
//        dict.put("Transaction currency", "TransCurrency");
//        dict.put("Exchange Rate 99v9999", "ExchangeRate");
//        dict.put("Branch Name", "BranchName");
//        dict.put("Transaction Number", "TransNo");
//        dict.put("Long Mnemonic", "LongMnemonic");
//        dict.put("Description (e.g. ‘0000’)", "Desc");
//        dict.put("其中：", "Data");
//        dict.put("Volume Number 数值", "VolumeNo");
//        dict.put("Cheque Number", "ChequeNo");
//        dict.put("Account Number", "AcctNo");
//        dict.put("Date (format ‘dd/mm/yyyy’)", "Date");
//        dict.put("Name", "Name");
//        dict.put("Asterisk – ‘*’", "Asterisk");
//        dict.put("Amount in words", "AmountInWords");
//        dict.put("\"Amount", "Amount");
//        dict.put("Constant:常量：", "Constant");
//        dict.put("Filler = Spaces", "Filler");
//        dict.put("Error Code", "ErrorCode");
//        dict.put("Filler = Spaces", "Filler");
//        dict.put("Error Message Text Override Code", "ErrorMsgCode");
//        dict.put("Filler = Spaces", "Filler");
//        dict.put("Error Message Text", "ErrorMsg");
//        dict.put("转出账号1的开户机构", "OutAcct1Inst");
//        dict.put("转出账号2的开户机构（多金融交易用）", "OutAcct2Inst");
//        dict.put("转出账号3的开户机构（多金融交易用）", "OutAcct3Inst");
//        dict.put("Passbook Type 存折类型", "PassbookType");
//        dict.put("Passbook Number 存折号码", "PassbookNo");
//        dict.put("New Passbook Indicator 新存折标志", "NewPassIndicator");
//        dict.put("New Page Indicator 新页标志", "NewPageIndicator");
//        dict.put("Volume Number 册号", "VolumeNo");
//        dict.put("Page Number页数", "PageNo");
//        dict.put("Line Number 行数", "LineNo");
//        dict.put("Date", "Date");
//        dict.put("Mnemonic", "Mnemonic");
//        dict.put("Flags the role of the particular deposit account type for Foregin Currency transfers", "Flag");
//        dict.put("Foreign Currency Account Currency", "ForeignCurrency");
//        dict.put("Withdrawal Transaction Amount", "WithdrawTransAmount");
//        dict.put("Deposit Transaction Amount", "DepositTransAmount");
//        dict.put("Account Balance", "AcctBalance");
//        dict.put("User (or Teller) Number", "TellerNo");
//        dict.put("Branch Number", "BranchNo");
//        dict.put("Out Line Number", "OutLineNo");
//        dict.put("子账户类别", "SubAcctType");
//        dict.put("册号 Volume NO", "VolumeNo");
//        dict.put("序号Serial NO", "SerialNo");
//        dict.put("冻结原因", "FreezeReason");
//        dict.put("数量Quantity", "Quantity");
//        dict.put("起始号码Start Number", "StartNo");
//        dict.put("终止号码End Number", "EndNo");
//        dict.put("旧账号", "OldAcct");
//        dict.put("转入账号", "InAcct");
//        dict.put("转出账号（内部账号 BGL）", "OutAcct");
//        dict.put("支票号码", "CheckNo");
//        dict.put("延迟利息天数", "DelayInterestDays");
//        dict.put("借记延迟利息天数", "DebitDelayInterestDays");
//        dict.put("不起息天数", "BQXDays");
//        dict.put("对账单摘要", "AccountDigest");
//        dict.put("产品子类", "ProductSubType");
//        dict.put("分层利率组别", "FCInterestGroup");
//        dict.put("利率加减点", "InterestJJD");
//        dict.put("定期续存类型", "FixSurviveType");
//        dict.put("初始凭证号码", "InitCertiNo");
//        dict.put("旧账号标识", "OldAcctId");
//        dict.put("Correction IND", "CorrectionIND");
//        dict.put("客户类型 Customer type", "CustType");
//        dict.put("Swift号", "SwiftNo");
//        dict.put("电传Telex", "Telex");
//        dict.put("起始记录号Start record number", "StartRecNo");
//        dict.put("选项", "Option");
//        dict.put("客户号Customer number3", "CustNo3");
//        dict.put("证件号码Certificate Number", "CertiNo");
//        dict.put("证件种类certificate type", "CertiType");
//        dict.put("RECNO", "RecNo");
//        dict.put("证件号Certificate Number", "CertiNo");
//        dict.put("证件种类CertificateType", "CertiType");
//        dict.put("旧帐号Old SignOldAcct", "OldAcctNo");
//        dict.put("签约新帐号", "ContractNewAcctNo");
//        dict.put("签约卡号", "ContractCardNo");
//        dict.put("签约子账户类别号", "ContractSubAcctTypeNo");
//        dict.put("签约账号册号", "ContractAcctBookNo");
//        dict.put("签约账号序号", "ContractAcctSeqNo");
//        dict.put("扣费旧帐号省代码", "KFOldAcctProvinceNo");
//        dict.put("扣费旧帐号", "KFOldAcctNo");
//        dict.put("扣费帐号新帐号", "KFNewAcctNo");
//        dict.put("扣费卡号", "KFCardNo");
//        dict.put("扣费子账户类别号", "KFSubAcctTypeNo");
//        dict.put("签约类型", "ContractType");
//        dict.put("签约解约标志", "ContractBreakId");
//        dict.put("核心签约索引号", "CoreContractIndexNo");
//        dict.put("签约描述信息", "ContractDesc");
//        dict.put("标识位", "SignPos");
//        dict.put("标识", "Sign");
//        dict.put("签约渠道", "ContractChannel");
//        dict.put("签约客户号", "ContractCustNo");
//        dict.put("签约证件类型", "ContractCertiType");
//        dict.put("签约证件号码", "ContractCertiNo");
//        dict.put("签约帐户名", "ContractAcctName");
//        dict.put("扣费证件类型", "KFCertiType");
//        dict.put("扣费证件号码", "KFCertiId");
//        dict.put("扣费帐户名", "KFAcctName");
//        dict.put("校验种类", "VerifyType");
//        dict.put("功能选项", "FuncOpt");
//        dict.put("签约编号", "ContractNo");
//        dict.put("签约标志", "ContractId");
//        dict.put("旧帐号", "OldAcct");
//        dict.put("旧账号偏移位置", "OffsetPos");
//        dict.put("转出账号", "OutAcctNo");
//        dict.put("余额", "Balance");
//        dict.put("转入BGL账号", "InBGLNo");
//        dict.put("扣款至最小余额标识", "ChargeBackMinAmountId");
//        dict.put("延迟记息天数", "DelayDays");
//        dict.put("借记延迟记息天数", "DebitDelayDays");
//        dict.put("DefaultString3", "DefaultString3");
//        dict.put("对帐单摘要", "DZDDigest");
//        dict.put("凭证类型", "CertType");
//        dict.put("凭证签发日期", "CertDate");
//        dict.put("子账户类别码", "SubAcctClassCode");
//        dict.put("", "Unknown");
//        dict.put("货币版本", "CurrencyVer");
//        dict.put("汇利率类型", "ExchangeRateType");
//        dict.put("汇率", "ExchangeRate");
//        dict.put("支付密码验证标志", "PayPassVerifId");
//        dict.put("旧账号标识,OldFlag", "OldFlag");
//        dict.put("客户类型Customer Type", "CustomerType");
//        dict.put("ID类型和号码ID type and number", "IDType");
//        dict.put("证件状态Certificate status", "CertState");
//        dict.put("证件签发日 Issuance date of certificate", "IssuanceDate");
//        dict.put("证件到期日Maturity date of certificate", "MaturityDate");
//        dict.put("证件发证机关Certificate-granting department", "CertGrantDepart");
//        dict.put("记录号", "RecordNo");
//        dict.put("卡号Card Number", "CardNo");
//        dict.put("卡持有人姓名", "CardOwnerName");
//        dict.put("卡产品描述", "CardProductDesc");
//        dict.put("卡持有人姓名", "CardOwnerName");
//        dict.put("卡序号", "CardSeq");
//        dict.put("卡激活", "CardActivate");
//        dict.put("卡状态描述", "CardState");
//        dict.put("等待分配标识", "ToIssueId");
//        dict.put("待制卡标识", "ToProduceId");
//        dict.put("制卡中标识", "ProduceId");
//        dict.put("已签发标识", "CertifyId");
//        dict.put("激活标识", "ActivateId");
//        dict.put("重发标识", "ResendId");
//        dict.put("到期重发标识", "ExpResendId");
//        dict.put("禁止到期重发标识", "ForbExpResendId");
//        dict.put("重发密码标识", "ResendPassId");
//        dict.put("已销卡标识", "CancelCardId");
//        dict.put("已到期标识", "ExpireId");
//        dict.put("已返回标识", "ReturnId");
//        dict.put("暂时止付标识", "TempZFId");
//        dict.put("黑名单止付标识", "BlackListZFId");
//        dict.put("完全止付标识", "CompleteZFId");
//        dict.put("临时挂失标识", "TempLossId");
//        dict.put("正式挂失标识", "FormalLossId");
//        dict.put("锁卡标识", "CardLockId");
//        dict.put("密码挂失标识", "PasswordLossId");
//        dict.put("吞卡标识", "CardRetianId");
//        dict.put("CVV校验错误校验错误标识", "CvvErrorId");
//        dict.put("卡名称第一栏", "CardName1");
//        dict.put("卡名称第二栏", "CardName2");
//        dict.put("发卡序号", "CardIssueSeq");
//        dict.put("主卡卡号", "CardNo");
//        dict.put("发卡机构", "CardIssueInst");
//        dict.put("主账户关联类型1", "LinkType1");
//        dict.put("主账户关联帐号1", "LinkAcct1");
//        dict.put("领卡机构", "CardInst");
//        dict.put("主账户关联类型2", "LinkType2");
//        dict.put("主账户关联帐号2", "LinkAcct2");
//        dict.put("主账户关联类型3", "LinkType3");
//        dict.put("主账户关联帐号3", "LinkAcct3");
//        dict.put("客户地址栏1", "CustAddr1");
//        dict.put("客户地址栏2", "CustAddr2");
//        dict.put("客户地址栏3", "CustAddr3");
//        dict.put("客户地址栏4", "CustAddr4");
//        dict.put("客户地址邮政编码", "CustZipCode");
//        dict.put("联系电话", "Tel");
//        dict.put("上次使用日期", "LastUseDate");
//        dict.put("发卡日期", "CardIssueDate");
//        dict.put("年费折扣", "NFDisccount");
//        dict.put("免年费期限", "MNFDeadline");
//        dict.put("暂时止付机构", "ZSZFInst");
//        dict.put("完全止付机构", "WQZFInst");
//        dict.put("Track2", "Track2");
//        dict.put("PIN", "PIN");
//        dict.put("Tstatus", "Tstatus");
//        dict.put("授权ID", "AuthId");
//        dict.put("IsOpenAccount", "IsOpenAccount");
//        dict.put("旧支取方式", "OldWithdrawMethod");
//        dict.put("旧密码", "OldPassword");
//        dict.put("新支取方式", "NewWithdrawMethod");
//        dict.put("新密码", "NewPassword");
//        dict.put("Offset position", "OffsetPos");
//        dict.put("交易起始号码", "TransBeginNo");
//        dict.put("交易类型", "TransType");
//        dict.put("交易起始日期", "TransBeginDate");
//        dict.put("交易终止日期", "TransTermDate");
//        dict.put("交易金额", "TransAmount");
//        dict.put("贷款账户", "LoanAccount");
//        dict.put("重整前到期日", "CZQDueDate");
//        dict.put("重整后到期日", "CZHDueDate");
//        dict.put("额度号（隐藏）", "EDH");
//        dict.put("重整前产品子类", "CZQProdSubClass");
//        dict.put("重整后产品子类", "CZHProdSubClass");
//        dict.put("重整金额", "CZAmount");
//        dict.put("重整状态", "CZState");
//        dict.put("重整前贷款期限 ", "CZQLoanDueDate");
//        dict.put("重整前产品大类", "CZQProductClass");
//        dict.put("重整前原固定利率", "CZQFixInterestRAte");
//        dict.put("重整前利率增量", "CZQInterestIncr");
//        dict.put("还款方式", "RepaymentMethod");
//        dict.put("重整前贷款余额", "CZQLoanAmount");
//        dict.put("还款日", "DueDate");
//        dict.put("重整后产品大类", "CZHProductClass");
//        dict.put("重整后贷款期限 ", "CZHLoanDueDate");
//        dict.put("新的固定利率", "FiXInterestRate");
//        dict.put("重整交易类型", "CZTransType");
//        dict.put("新的利率增量", "NewInterestIncr");
//        dict.put("利率增量选项", "InterestIncrOpt");
//        dict.put("页面标识PageFlag", "PageFlag");
//        dict.put("产品描述", "ProductDesc");
//        dict.put("使用者代码", "UserCode");
//        dict.put("账户状态", "AcctState");
//        dict.put("投资类型", "InvestType");
//        dict.put("地区", "Area");
//        dict.put("代理号", "ProxyNo");
//        dict.put("通知标识", "InfomId");
//        dict.put("邮递标识", "PostId");
//        dict.put("地址1", "Address1");
//        dict.put("已付利息1", "PayedInterest1");
//        dict.put("地址2", "Address2");
//        dict.put("已付利息2", "PayedInterest2");
//        dict.put("地址3", "Address3");
//        dict.put("已付利息3", "PayedInterest3");
//        dict.put("地址4", "Address4");
//        dict.put("适用利率", "SYInterestRate");
//        dict.put("已付利息4", "PayedInterest4");
//        dict.put("贷方利率", "DFInterestRate");
//        dict.put("借方利率", "JFInterestRate");
//        dict.put("已付利息5", "PayedInterest5");
//        dict.put("filler", "Filler");
//        dict.put("透支期满日期", "OverdraftDate");
//        dict.put("filler", "Filler");
//        dict.put("冻结金额", "FreezeAmount");
//        dict.put("透支限额", "OverdraftQuota");
//        dict.put("贷记利息增量", "DJLXIncrement");
//        dict.put("上次付息日", "LastPayDay");
//        dict.put("关户利息", "GHInterest");
//        dict.put("预估利息", "YGInterest");
//        dict.put("下次付息日", "NextInterest");
//        dict.put("应扣税", "YKTax");
//        dict.put("应付利息", "YFInterest");
//        dict.put("开户柜员", "OpenTeller");
//        dict.put("开户柜员标识", "OpenTellerId");
//        dict.put("适用利率", "GYInterestRate");
//        dict.put("上次账户变更类别日期", "LastAccTypeChangeDate");
//        dict.put("应收透支息", "YSTZX");
//        dict.put("可用余额", "AvailBalance");
//        dict.put("ACCT-COND", "AcctCond");
//        dict.put("拒付支票Cancel Check Dishonor Count", "CancelCheckDishonorCnt");
//        dict.put("机构号信息标识", "InstNoInfoId");
//        dict.put("凭证版本号PSBK Version NO", "PSBKVerNo");
//        dict.put("CHOP状态 CHOP status", "ChopStatus");
//        dict.put("印鉴状态", "SigatureState");
//        dict.put("复利利率", "CompoundRate");
//        dict.put("账户类别", "AcctType");
//        dict.put("INT-CAT", "IntCat");
//        dict.put("凭证状态", "CertState");
//        dict.put("Offset Position", "OffsetPos");
//        dict.put("子帐户类别", "SubAcctType");
//        dict.put("选项Option", "Option");
//        dict.put("子账户信息", "SubAcctInfo");
//        dict.put("客户号", "CustNo");
//        dict.put("证件号码、类型", "IdNum");
//        dict.put("子帐号类型", "SubAccountType");
//        dict.put("国籍", "Nationality");
//        dict.put("人民币结算账户属性", "RMBSettleProp");
//        dict.put("账户所属机构号", "InstitutionNo");
//        dict.put("客户性质别", "CustProp");
//        dict.put("帐户类型", "AccountType");
//        dict.put("账户子类", "AccountSubType");
//        dict.put("开户日期", "OpenDate");
//        dict.put("有效日期", "ValidDate");
//        dict.put("冻结到期日", "FreezeDay");
//        dict.put("定期存款资金来源帐号", "FixDepSrcAcctNo");
//        dict.put("存期", "DepositPeriod");
//        dict.put("基期", "JQ");
//        dict.put("取息频率", "InterestFreq");
//        dict.put("定存续存", "FixSurviving");
//        dict.put("定存到期通知", "FixDueDate");
//        dict.put("到期日期", "DueDate");
//        dict.put("利率变更通知标识", "InterstChangeSign");
//        dict.put("利率类型", "InterestType");
//        dict.put("群组号", "GroupNo");
//        dict.put("议价利率", "YJInterestRate");
//        dict.put("利率周期", "InterestPeriod");
//        dict.put("转息方式", "ZXMethod");
//        dict.put("转账帐号", "TransferNo");
//        dict.put("客户限额编码", "CustLimitNo");
//        dict.put("客户利率加码", "CustInterestJM");
//        dict.put("透支记息方式", "OverdraftMethod");
//        dict.put("透支连接标识", "OverdraftConnSign");
//        dict.put("综存透支", "ZCOverdraft");
//        dict.put("应用ID", "AppId");
//        dict.put("收费减免编号", "FeeReduceNo");
//        dict.put("通知处理编号", "InformProcNo");
//        dict.put("通知编号", "InformNo");
//        dict.put("通知客户", "InformCustomer");
//        dict.put("循环", "Cycle");
//        dict.put("天数", "Day");
//        dict.put("份数", "Quota");
//        dict.put("语言代码", "LangCode");
//        dict.put("邮政标识", "PostCode");
//        dict.put("代理人代码", "ProxyCode");
//        dict.put("区域", "Area");
//        dict.put("分组标识", "GroupSign");
//        dict.put("抵押标识", "MortgageSign");
//        dict.put("外币账户性质", "WBAccountProp");
//        dict.put("账号", "AccountNo");
//        dict.put("册号", "BookNo");
//        dict.put("序号", "SequenceNo");
//        dict.put("验证账号状态", "VerfiAccState");
//        dict.put("验证账号是否冻结", "VerfiAccFreeze");
//        dict.put("Settlement Type Acct", "SettlementTypeAcct");
//        dict.put("验证凭证挂失状态", "VeriPZGSState");
//        dict.put("支取方式", "ZQMethod");
//        dict.put("验证支取方式", "VeriZQMethod");
//        dict.put("证件类型", "IdType");
//        dict.put("证件号码", "IdNum");
//        dict.put("验证证件信息", "VeriIdInfo");
//        dict.put("LastType", "LastType");
//        dict.put("LastPrefix", "LastPrefix");
//        dict.put("LastNum", "LastNum");
//        dict.put("LastStatus", "LastStatus");
//        dict.put("PB状态", "PbState");
//        dict.put("重空类型描述", "ZKTypeDesc");
//        dict.put("重空类型值", "ZKTypeValue");
//        dict.put("重空数量", "ZKAmount");
//        dict.put("价值", "Value");
//        dict.put("重空起始号码", "ZKBeginNo");
//        dict.put("重空终止号码", "ZKStopNo");
//        dict.put("重空状态描述", "ZKStateDesc");
//        dict.put("重空状态值", "ZKStateValue");
//        dict.put("PD号", "PKNo");
//        dict.put("重控类型", "ZLType");
//        dict.put("客户名称(中文) Customer name(in Chinese)", "CustomerName");
//        dict.put("行业分类Industry classification", "IndustryClass");
//        dict.put("注册国家Registered country", "RegCountry");
//        dict.put("企业性质Enterprise attribute", "EntAttribute");
//        dict.put("企业经济成分Sector of economy of enterprise", "SecEcoEnt");
//        dict.put("法人代表姓名Legal person name", "LegPersonName");
//        dict.put("法人代表证件类型Type of legal person certificate", "LegPersonCertType");
//        dict.put("法人代表证件号码Number of legal person certificate", "LegPersonCertNo");
//        dict.put("联系人姓名Contact name", "ContactName");
//        dict.put("联系人电话Contact telephone number", "ContactTel");
//        dict.put("联系人电子邮件Contact e-mail", "ContactEmail");
//        dict.put("主营业务Primary business", "PrimaryBusiness");
//        dict.put("财务负责人Financial principal", "FinancialPrincipal");
//        dict.put("财务负责人电话Financial principal telephone number", "FinPrincTelNo");
//        dict.put("注册资本金额Registered capital amount", "RegCapitalAmount");
//        dict.put("注册资本货币Registered capital currency", "RegCapitalCurrency");
//        dict.put("审核柜员", "AuditTeller");
//        dict.put("审核柜员PIN", "AuditTellerPIN");
//        dict.put("转出存款帐号", "OutAccountNo");
//        dict.put("账户余额", "AccountBalance");
//        dict.put("提示码promono", "Promono");
//        dict.put("内部收费BGL账号", "NBSFBGLNo");
//        dict.put("费用类型", "FeeType");
//        dict.put("备注", "Remark");
//        dict.put("汇率类型", "ExchangeRateType");
//        dict.put("BGl帐号", "BGLNo");
//        dict.put("金额amount", "Amount");
//        dict.put("说明", "Explanation");
//        dict.put("名称1", "Name1");
//        dict.put("名称2", "Name2");
//        dict.put("提示码", "HintCode");
//        dict.put("转出币种", "OutCurrency");
//        dict.put("兑换金额", "ExchangeAmount");
//        dict.put("转入币种", "InCurrency");
//        dict.put("本币金额", "DomesticAmount");
//        dict.put("佣金", "Commision");
//        dict.put("找零", "Change");
//        dict.put("汇(利)率类型", "InterestRateType");
//        dict.put("货币版本 Currency Version", "CurrencyVersion");
//        dict.put("账号/支票号码", "AccountNo");
//        dict.put("Segment Code", "SegmentCode");
//        dict.put("stmtnrtv1对帐单摘要", "Stmtnrtvl");
//        dict.put("现金统计分析码", "XJTJFXNo");
//        dict.put("上存联社账号", "SCLSZH");
//        dict.put("存放上级账号", "CFSJZH");
//        dict.put("调入县辖资金账号", "DRXXZJZH");
//        dict.put("上存户上日余额", "SCHSRBalance");
//        dict.put("存放户上日余额", "CFHSRBalance");
//        dict.put("查询余额", "QueryBalance");
//        dict.put("当日发生额", "DRFSAmount");
//        dict.put("状态", "State");
//        dict.put("卡号", "CardNo");
//        dict.put("密码", "Password");
//        dict.put("Action", "Action");
//        dict.put("读磁", "ReadTrack");
//        dict.put("显示页码标志", "XSYMSign");
//        dict.put("金融标志", "FinanceSign");
//        dict.put("电话银行标志", "TelBankSign");
//
//        dict.put("转出帐号", "OutAccoutNo");
//        dict.put("省代码/转出方", "ProvinceNoOut");
//        dict.put("转出旧帐号", "OutOldAccountNo");
//        dict.put("转出帐号系统", "OutAccountSys");
//        dict.put("子账户类型", "SubAccountType");
//        dict.put("转入帐号", "InAccountNo");
//        dict.put("省代码/转入方", "ProvinceNoIn");
//        dict.put("转入旧帐号", "InOldAccountNo");
//        dict.put("转入帐号系统", "InAccountSys");
//        dict.put("产品类型", "ProductType");
//        dict.put("产品子类型", "ProductSubType");
//        dict.put("金额", "Amount");
//        dict.put("提示吗", "HintCode");
//        dict.put("重空类型", "CKType");
//        dict.put("重空号码", "CKNo");
//        dict.put("重空密码", "CKPassword");
//        dict.put("支付方式", "PaymentMethod");
//        dict.put("备注stmtnrtv", "Remark");
//
//        dict.put("CUST_NO客户号", "CustomerNo");
//        dict.put("CUST_TYPE客户类型", "CustomerType");
//        dict.put("ID_NUM证件号码", "IdNum");
//        dict.put("ID_TYPE证件类型", "IdType");
//        dict.put("CUST_NAME姓名", "CustomerName");
//        dict.put("VIP_CODE VIP代码", "VipCode");
//        dict.put("VIP_GEO VIP地域", "VipGeo");
//        dict.put("VIP_REB_RATE优惠比率", "VipRebRate");
//        dict.put("VIP-UNION-CODE", "VipUnionCode");
//        dict.put("CUST_NO客户号码/账号1", "CustomerNo");
//        dict.put("C_A_FLAG客户号/账号", "CaFlag");
//        dict.put("旧账号偏移位offset", "OldAccountOffset");
//        dict.put("客户帐号", "CustomerAccount");
//        dict.put("册号Volume NO", "VolumeNo");
//        dict.put("打印选项", "PrintOption");
//        dict.put("功能", "Function");
//        dict.put("清算机构号", "ClearInstitutionNo");
//        dict.put("币种", "Currency");
//        dict.put("客户号Customer number", "CustomerNo");
//        dict.put("客户类型Customer type", "CustomerType");
//        dict.put("客户子类型Customer sub-type", "CustomerSubType");
//        dict.put("证件类型Certificate type", "CertificateType");
//        dict.put("证件号码Certificate number", "CeritficateNo");
//        dict.put("所属行 Bank", "Bank");
//        dict.put("客户状态Customer status", "CustomerStatus");
//        dict.put("客户状态2 Customer status 2", "CustomerStatus2");
//        dict.put("客户状态3 Customer status 3", "CustomerStatus3");
//        dict.put("通讯语言 Communication language", "CommLang");
//        dict.put("开户行Account-open  bank", "AccountOpenBank");
//        dict.put("最后更新日期Last update date", "LastUpdateDate");
//        dict.put("最后更新柜员 Last update teller", "LastUpdateTeller");
//        dict.put("最后更新柜员所属行 Branch of last update teller", "BranchOfLastUupdateTeller");
//        dict.put("员工标识 Staff flag", "StaffFlag");
//        dict.put("姓/Family name", "FamilyName");
//        dict.put("名/First name", "FirstName");
//        dict.put("其他名称 Other name", "OtherName");
//        dict.put("国籍Nationality", "Nationality");
//        dict.put("性别Gender", "Gender");
//        dict.put("居民/非居民Resident/ non-resident", "Resident");
//        dict.put("综合对账单周期Check sheet Frequency", "CheckSheetFreq");
//        dict.put("循环Cycle", "Cycle");
//        dict.put("天Day", "Day");
//        dict.put("综合对账单发送方式 Sending method for comprehensive check sheet", "ZHDZDFSFS");
//        dict.put("综合对账单地址编号 Address No of comprehensive check sheet", "ZHDZDDZBH");
//        dict.put("持有保管箱 Hold Safe deposit box", "CYBGX");
//        dict.put("利息税优惠标识  Flag of preferential interest tax", "LXSYHBS");
//        dict.put("利息税优惠到期日 Maturity date of preferential interest tax", "LXSYHDQR");
//        dict.put("个人月收入  Monthly individual income", "MonthlyIncome");
//        dict.put("婚姻状况 Marital status", "MartialStatus");
//        dict.put("报告日期Report data", "ReportDate");
//        dict.put("税收类型", "TaxType");
//
//        dict.put("客户号或账号Customer number or Account number", "GustOrNoAccNo");
//        dict.put("客户类型", "CustomerType");
//        dict.put("客户账户标识Flag", "CustomerSignFlag");
//        dict.put("PandNo1", "PandNo1");
//        dict.put("查询类型Inquiry type", "InquiryType");
//        dict.put("起始记录号 Start record No.", "StartRecordNo");
//        dict.put("产品群组Porducte Group", "ProductGroup");
//        dict.put("终止记录号", "StopRecordNo");
//        dict.put("记录号    Record Number", "RecordNo");
//        dict.put("群组号     Group Number", "GroupNo");
//        dict.put("选项2", "Option2");
//        dict.put("证件号Certificate number", "CertificateNumber");
//        dict.put("证件种类Certificate type", "CeritficateType");
//
//        dict.put("省代码", "ProvinceCode");
//        dict.put("旧帐号Old Account NO", "OldAccountNo");
//        dict.put("Offset", "Offset");
//        dict.put("子帐户类别Sub-account Type", "SubAccountType");
//        dict.put("册号Volume No.", "VolumeNo");
//        dict.put("序号Serial No.", "SerialNo");
//        dict.put("功能选项Functional Option", "FunctionalOption");
//        dict.put("DefInteger1", "DefInteger1");
//        dict.put("DefInteger2", "DEfInteger2");
//        dict.put("promono1", "Promono1");
//        dict.put("旧账号标识oldflag", "OldFlag");
//        dict.put("Terminal ID", "TerminalId");
//        dict.put("Terminal Type", "TerminalType");
//        dict.put("Risk Sms Flag", "RistSmsFlag");
//        dict.put("Card NO", "CardNo");
//
//        dict.put("帐号", "AccountNo");
//        dict.put("货币类型", "CurrencyType");
//        dict.put("账户状态描述", "AccountState");
//        dict.put("机构号", "InstitutionNo");
//        dict.put("账户类型", "AccountType");
//        dict.put("帐户类别编号", "AccountClassifyNo");
//        dict.put("子类", "SubClass");
//        dict.put("Int Meth", "IntMeth");
//        dict.put("利息方式", "IntMeth");
//        dict.put("利率", "InterestRate");
//        dict.put("账户名称", "AccountName");
//        dict.put("客户名称", "CustomerName");
//        dict.put("宅电", "Tel");
//        dict.put("办公电话", "OfficeTel");
//        dict.put("开户日", "OpenDay");
//        dict.put("上次账户信息变更日期", "LastAccountChangeDate");
//        dict.put("上次金融交易日期", "LastExchangeDate");
//        dict.put("上一结息日", "LastSettleDate");
//        dict.put("下一结息日", "NextSettleDate");
//        dict.put("开户记帐日期", "OpenAccountDate");
//        dict.put("当前余额", "CurrentBalance");
//        dict.put("未清算资金", "UnclearedAmount");
//        dict.put("未登折金额", "NpbAmount");
//        dict.put("应计贷方利息", "YJDFInterest");
//        dict.put("已登折余额", "YDZBalance");
//        dict.put("不计息金额", "BJXAmount");
//        dict.put("通胀余额(不用)", "TZBalance");
//        dict.put("调整上期利息额", "TZSQInterestAmount");
//        dict.put("定制支票簿(不用)", "DZCheckBook");
//        dict.put("定期支票(不用)", "DZCheck");
//        dict.put("本年度利息", "BNDInterest");
//        dict.put("上次超透支额度日期", "SCCTZEDDate");
//        dict.put("本年度居民利息税", "BNDJMInterestTax");
//        dict.put("本年度非居民利息税", "BNDFJMInterestTax");
//        dict.put("授信额度(不用)", "SXCredit");
//        dict.put("当前Visa借记利息(不用)", "VisaTax");
//        dict.put("可用贷方金额", "KYDFAmount");
//        dict.put("当前购买次数(不用)", "DQGMCount");
//        dict.put("已支付最小金额", "PayedMinAmount");
//        dict.put("目前现金发放次数(不用)", "CashIsuranceCount");
//        dict.put("C/A 利息申请", "CAInterestApplication");
//        dict.put("Purch Int Applied", "PurchIntApplied");
//        dict.put("安全代码(VISA(不用))", "SecurityCode");
//        dict.put("Filler", "Filler");
//        dict.put("新机构号", "NewInstitutionNo");
//        dict.put("对账单周期", "CheckingPeriod");
//        dict.put("周期", "Period");
//        dict.put("天", "Day");
//        dict.put("凭证号码", "CertificationNo");
//        dict.put("存折行号", "BankbookNo");
//        dict.put("协议存单(台湾版(不用))", "XYDeposit");
//        dict.put("(台湾版(不用))", "TaiwanVer");
//        dict.put("Filler", "Filler");
//        dict.put("开户记帐日期", "OpenDayAccountDate");
//        dict.put("总账分类码", "ZZFLCode");
//        dict.put("上次账户类型变更日期", "LastAccTypeChangeDate");
//        dict.put("应计借方利息", "YJJFInterest");
//        dict.put("Filler", "Filler");
//        dict.put("AvaBalance", "AvaBalance");
//        dict.put("定制支票簿(不用)", "DZCheckBook");
//        dict.put("Cancel Check Dishonor Count （待确认）", "CancelCheckDishonorCount");
//        dict.put("分行标识", "BranchBankSign");
//        dict.put("存折版本号", "BankbookVer");
//        dict.put("存折版本/状态", "BankBookState");
//        dict.put("印鉴状态(不用)", "SignatureState");
//        dict.put("存单号（待测试）", "DepositNo");
//        dict.put("存单状态（不用）", "DepositState");
//        dict.put("账户状态值", "AccountState");
//        dict.put("协议签署日期", "SignDate");
//        dict.put("复杂TD（不用）", "ComplicateTD");
//        dict.put("黑名单日期", "BlackListDate");
//        dict.put("定存到期息", "DCDQInterst");
//        dict.put("未支付利息", "WZFInterest");
//        dict.put("放弃抵消/无效付款人标记（待确认）", "FQDX");
//        dict.put("特殊转账限制标示", "SpecialTransferLimitSign");
    }
}
