package com.y3r9.c47.dog.demo.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-05-25T23:15:15.310+08:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://ttdev.com/ss", name = "SimpleService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SimpleService {

    @WebResult(name = "concatResponse", targetNamespace = "http://ttdev.com/ss", partName = "parameters")
    @WebMethod(action = "http://ttdev.com/ss/NewOperation")
    public java.lang.String concat(
        @WebParam(partName = "parameters", name = "concatRequest", targetNamespace = "http://ttdev.com/ss")
        ConcatRequest parameters
    );
}
